apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: kube-public
  name: traefik-rbac
  labels:
        app: traefik
rules:
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list]